# -*- coding: utf-8 -*-
"""crops_all_submit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qblg4k6dZeXcJnEC18qRnVMIHdMIoVmz
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import statsmodels.api as sm

# Load the dataset
data_path = '/content/drive/MyDrive/ColabNotebooks/input/Production_Crops_Livestock_E_All_Data.csv'
filtered_data = pd.read_csv(data_path, encoding='latin1')

# Define columns for years (1992-2021) and their corresponding flags
year_columns = [f'Y{year}' for year in range(1992, 2022)]
flag_columns = [f'Y{year}F' for year in range(1992, 2022)]

# Select only relevant columns: area, area code, item, element, and year/flag columns
filtered_data = filtered_data[['Area', 'Area Code (M49)', 'Item', 'Element'] + year_columns + flag_columns]

# Load the table of item groups to filter only crop-related items
item_groups = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/FAOSTAT_data_9-14-2023.csv')

# Define the desired crop groups to include in the analysis
desired_groups = [
    "Cereals, primary", "Fruit Primary", "Vegetables Primary",
    "Pulses, Total", "Oilcrops Primary", "Sugar Crops Primary", "Roots and Tubers, Total"
]

# Filter items that belong to the desired groups or are specifically "Other stimulant, spice and aromatic crops, n.e.c."
filtered_items = item_groups[
    (item_groups['Item Group'].isin(desired_groups)) |
    (item_groups['Item'] == "Other stimulant, spice and aromatic crops, n.e.c.")
]

# Exclude items whose name matches the name of the group (to avoid duplicates or aggregation errors)
filtered_items = filtered_items[filtered_items['Item'] != filtered_items['Item Group']]

# Filter the main dataset to include only rows where the item is in the filtered items list
filtered_data = filtered_data[filtered_data['Item'].isin(filtered_items['Item'])]

# 1. Filter the dataset to include only rows where "Element" is "Area harvested"
yield_data = filtered_data[filtered_data['Element'] == 'Area harvested']

# 2. Group the data by country and check if there is any data (non-NA) for all years in the range
valid_countries = yield_data.groupby('Area').apply(lambda group: all(group[year_columns].notna().any())).reset_index()
valid_countries.columns = ['Area', 'Valid']

# 3. Filter the dataset to include only countries with valid data for all years in the specified range
valid_countries_list = valid_countries[valid_countries['Valid']]['Area'].tolist()
filtered_data = filtered_data[filtered_data['Area'].isin(valid_countries_list)]

# Create a table of unique items and their associated groups
filtered_items = item_groups[['Item', 'Item Group']].drop_duplicates()

# Merge the item group information into the filtered data
filtered_data = filtered_data.merge(filtered_items, on='Item', how='left')

# Rename the 'Item Group' column to 'item_group' for clarity
filtered_data = filtered_data.rename(columns={'Item Group': 'item_group'})

# Remove duplicate rows based on specific columns to ensure data consistency
filtered_data = filtered_data.drop_duplicates(subset=['Area', 'Area Code (M49)', 'Item', 'Element', *year_columns])

# Display the filtered dataset and the unique items in the final dataset
filtered_data
print(filtered_data['Item'].unique())

# List of codes to be removed
codes_to_remove = [
    "'001", "'002", "'014", "'017", "'015", "'018", "'011", "'019", "'021", "'013", "'029", "'005",
    "'142", "'143", "'030", "'034", "'035", "'145", "'150", "'151", "'154", "'039", "'155", "'009",
    "'053", "'054", "'057", "'061", "'097", "'199", "'432", "'722", "'901", "'902"
]

# Filter the DataFrame to remove entries with the specified codes
filtered_data = filtered_data[~filtered_data['Area Code (M49)'].isin(codes_to_remove)]

# Load the table of country codes
country_codes = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/country_code.csv')

# Remove the initial quotation mark and convert the 'Area Code (M49)' column to integers
filtered_data['Area Code (M49)'] = filtered_data['Area Code (M49)'].str.replace("'", '').astype(int)

# Merge the country codes table with 'filtered_data' using 'Numericcode' and 'Area Code (M49)' as keys
final_df = filtered_data.merge(
    country_codes[['Alpha-2code', 'Alpha-3code', 'Numericcode']],
    left_on='Area Code (M49)',
    right_on='Numericcode',
    how='left'
)

final_df

######################################### SHANNON INDEX

yield_data = final_df[final_df['Element'] == 'Area harvested']


# List of year columns
year_columns = ['Y' + str(year) for year in range(1992, 2022)]

# Group the data by country ('Alpha-3code') and item, and sum values across the years
grouped_data = yield_data.groupby(['Alpha-3code', 'Item'])[year_columns].sum()

# Function to calculate the Shannon Index for a group
def shannon_index(group):
    total = group.sum()  # Calculate the total sum of the group
    proportions = group / total  # Calculate the proportions of each value
    proportions = proportions[proportions > 0]  # Filter out zero proportions
    return -np.sum(proportions * np.log(proportions))  # Calculate the Shannon Index

# Calculate the Shannon Index for each country and year (grouped by 'Alpha-3code' and 'Item')
shannon_indices = grouped_data.groupby('Alpha-3code').apply(lambda x: x.apply(shannon_index))

# Calculate the average Shannon Index across years for each country
shannon_avg = shannon_indices[year_columns].mean(axis=1).to_frame(name='shannon_avg_item_all')
shannon_avg = shannon_avg.reset_index()

# Merge the average Shannon Index for items into the final DataFrame
final_df = final_df.merge(shannon_avg, on='Alpha-3code', how='left')

# Group the data by country ('Alpha-3code') and item group, and sum values across the years
grouped_data = yield_data.groupby(['Alpha-3code', 'item_group'])[year_columns].sum()

# Function to calculate the Shannon Index for a group (same function as above)
def shannon_index(group):
    total = group.sum()  # Calculate the total sum of the group
    proportions = group / total  # Calculate the proportions of each value
    proportions = proportions[proportions > 0]  # Filter out zero proportions
    return -np.sum(proportions * np.log(proportions))  # Calculate the Shannon Index

# Calculate the Shannon Index for each country and year (grouped by 'Alpha-3code' and 'item_group')
shannon_indices = grouped_data.groupby('Alpha-3code').apply(lambda x: x.apply(shannon_index))

# Calculate the average Shannon Index across years for each country (for item groups)
shannon_avg = shannon_indices[year_columns].mean(axis=1).to_frame(name='shannon_avg_itemgroup_all')
shannon_avg = shannon_avg.reset_index()

# Merge the average Shannon Index for item groups into the final DataFrame
final_df = final_df.merge(shannon_avg, on='Alpha-3code', how='left')

# Final DataFrame with Shannon Index for items and item groups added

final_df = final_df.reset_index()[['Area', 'Area Code (M49)', 'Alpha-2code', 'Alpha-3code', 'shannon_avg_item_all','shannon_avg_itemgroup_all' ]]
final_df = final_df.drop_duplicates(subset='Area', keep='first')
final_df


################# HARVESTED


# Select the latest year (2021) for each crop type in each country
area_per_crop = yield_data.groupby(['Area Code (M49)', 'Item'])['Y2021'].sum().reset_index()

# Sum these values for each country
area_country = area_per_crop.groupby('Area Code (M49)')['Y2021'].sum().reset_index()

# Rename the column to 'main_Harvested_Area'
area_country.rename(columns={'Y2021': 'Total_Harvested_Area'}, inplace=True)
final_df = final_df.merge(area_country[['Area Code (M49)', 'Total_Harvested_Area']], on='Area Code (M49)', how='left')



final_df=final_df.round(3)

from google.colab import files

final_df.to_csv('crops_all.csv')
files.download('crops_all.csv')