# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.


"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import statsmodels.api as sm

# Load the dataset
data_path = '/content/drive/MyDrive/ColabNotebooks/input/Production_Crops_Livestock_E_All_Data.csv'
filtered_data = pd.read_csv(data_path, encoding='latin1')

# Filter the columns containing yield data from the year 2000 to 2021
year_columns = [f'Y{year}' for year in range(1992, 2022)]
flag_columns = [f'Y{year}F' for year in range(1992, 2022)]
filtered_data = filtered_data[['Area', 'Area Code (M49)', 'Item', 'Element'] + year_columns + flag_columns]
filtered_data
filtered_items = ["Barley", "Cassava, fresh", "Groundnuts, excluding shelled", "Maize (corn)", "Millet",
                  "Oil palm fruit", "Potatoes", "Rape or colza seed", "Rice", "Rye", "Sorghum",
                  "Soya beans", "Sugar beet", "Sugar cane", "Sunflower seed", "Wheat"]

# Load the item groups table (to keep only those that represent crops)
item_groups = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/FAOSTAT_data_9-14-2023.csv')

# List of item groups to remove
groups_to_remove = ["Crops, primary", "Oilcrops, Cake Equivalent", "Oilcrops, Oil Equivalent", "Crops Processed"]

# Remove rows where "Item Group" is in groups_to_remove
item_groups = item_groups[~item_groups['Item Group'].isin(groups_to_remove)]

# Show the first rows to verify the changes


# Filter 'filtered_data' to keep only the items that are in 'filtered_items'
filtered_data = filtered_data[filtered_data['Item'].isin(filtered_items)]

# 1. Filter the dataset to include only rows with "Area harvested" in the "Element" column
yield_data = filtered_data[filtered_data['Element'] == 'Area harvested']

# 2. Group by country and year, and check if there is any data (non-NA) for that year
valid_countries = yield_data.groupby('Area').apply(lambda group: all(group[year_columns].notna().any())).reset_index()
valid_countries.columns = ['Area', 'Valid']

# 3. Filter those countries that have data for all years in the specified range
valid_countries_list = valid_countries[valid_countries['Valid']]['Area'].tolist()
filtered_data = filtered_data[filtered_data['Area'].isin(valid_countries_list)]

# Add item group information to the filtered data
filtered_group = item_groups[['Item', 'Item Group']].drop_duplicates()
filtered_data = filtered_data.merge(filtered_group, on='Item', how='left')

# Rename the "Item Group" column to "item_group"
filtered_data = filtered_data.rename(columns={'Item Group': 'item_group'})

# Show the results
filtered_data

# List of codes to be removed, they belong to regions and continents, no countries
codes_to_remove = [
    "'001", "'002", "'014", "'017", "'015", "'018", "'011", "'019", "'021", "'013", "'029", "'005",
    "'142", "'143", "'030", "'034", "'035", "'145", "'150", "'151", "'154", "'039", "'155", "'009",
    "'053", "'054", "'057", "'061", "'097", "'199", "'432", "'722", "'901", "'902"]

# Filter the DataFrame to remove entries with the specified codes
filtered_data = filtered_data[~filtered_data['Area Code (M49)'].isin(codes_to_remove)]

# Load the country codes table
country_codes = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/country_code.csv')

# Remove the initial quotation mark and convert to integer
filtered_data['Area Code (M49)'] = filtered_data['Area Code (M49)'].str.replace("'", '').astype(int)

# Merge the country codes table with filtered_data using 'Numeric code' and 'Area Code (M49)'
filtered_data = filtered_data.merge(country_codes[['Alpha-2code', 'Alpha-3code', 'Numericcode']],
                                    left_on='Area Code (M49)', right_on='Numericcode', how='left')

final_df = filtered_data.reset_index()[['Area', 'Area Code (M49)', 'Alpha-2code', 'Alpha-3code']]
final_df

################################### Proportion of estimated data
yield_data = filtered_data[filtered_data['Element'] == 'Area harvested']
## Function to calculate the proportion of values ​​that are neither 'A' nor 'X' for each country and year, X=Value from international sources, A=Official Value, we get the proportion of estimated values
def calculate_non_ax_proportion(row):
    non_ax_count = sum(value not in ['A', 'X', ''] for value in row)
    total_count = len(row)
    return non_ax_count / total_count if total_count > 0 else 0

# proportion of flags per country
non_ax_proportions = yield_data[flag_columns].apply(calculate_non_ax_proportion, axis=1)
yield_data['non_ax_proportion'] = non_ax_proportions
non_ax_proportions_avg = yield_data.groupby('Area Code (M49)')['non_ax_proportion'].mean()
flags_proportion_avg = non_ax_proportions_avg.to_frame(name='yield_flags_proportion')


final_df = final_df.merge(flags_proportion_avg, left_on='Area Code (M49)', right_index=True, how='left')

####################### YIELD GAP TREND AND AVERAGE
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np
from scipy import stats

# Load the dataset containing yield gap data
yield_gap = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/ponderated_gap.csv')
yield_data = filtered_data[filtered_data['Element'] == 'Area harvested']
# Initialize a linear regression model
model = LinearRegression()

# Function to calculate the relative trend of yield gap for each group (country)
def calculate_relative_trend(group):
    # Ensure the data is sorted by year
    group = group.sort_values(by='Year')

    # Reshape the year column to fit the scikit-learn model
    X = group['Year'].values.reshape(-1, 1)
    y = group['AverageWeightedYieldGap'].values

    # Fit the linear regression model to calculate the trend (slope)
    model.fit(X, y)
    trend = model.coef_[0]

    # Retrieve the first value of 'AverageWeightedYieldGap', use 0.1 to avoid division by zero if the value is 0
    first_value = y[0] if y[0] != 0 else 0.1

    # Calculate the relative trend as the slope divided by the first value
    relative_trend = trend / first_value

    # Return a series with the calculated metrics
    return pd.Series({
        'Relative_yield_gap_trend': relative_trend,    # Relative yield gap trend
    })

# Apply the trend calculation function to each group (grouped by 'Alpha-3code')
relative_trends = yield_gap.groupby('Alpha-3code').apply(calculate_relative_trend).reset_index()

# Calculate the average yield gap per country
average_yield_gap_per_country = yield_gap.groupby('Alpha-3code')['AverageWeightedYieldGap'].mean().reset_index()

# Merge the average yield gap with the final DataFrame
final_df = final_df.merge(average_yield_gap_per_country, on='Alpha-3code', how='left')

# Merge the relative trends into the final DataFrame
final_df = final_df.merge(relative_trends, on='Alpha-3code', how='left')

# Display the columns in the final DataFrame
print(final_df.columns)

######################################### SHANNON INDEX MAIN CROPS
# List of year columns
year_columns = ['Y' + str(year) for year in range(1992, 2022)]

# Group the data by country (Alpha-3code) and item
grouped_data = yield_data.groupby(['Alpha-3code', 'Item'])[year_columns].sum()

# Function to calculate the Shannon Index for a group
def shannon_index(group):
    total = group.sum()  # Calculate the total sum of the group
    proportions = group / total  # Calculate the proportions
    proportions = proportions[proportions > 0]  # Filter out zero proportions
    return -np.sum(proportions * np.log(proportions))  # Calculate the Shannon Index

# Calculate the Shannon Index for each country and year (grouped by Alpha-3code and item)
shannon_indices = grouped_data.groupby('Alpha-3code').apply(lambda x: x.apply(shannon_index))

# Calculate the average Shannon Index across years for each country
shannon_avg = shannon_indices[year_columns].mean(axis=1).to_frame(name='shannon_avg_item')
shannon_avg = shannon_avg.reset_index()

# Merge the average Shannon Index (by item) into the final DataFrame
final_df = final_df.merge(shannon_avg, on='Alpha-3code', how='left')

# Group the data by country (Alpha-3code) and item group
grouped_data = yield_data.groupby(['Alpha-3code', 'item_group'])[year_columns].sum()

# Function to calculate the Shannon Index for a group (repeated for item groups)
def shannon_index(group):
    total = group.sum()  # Calculate the total sum of the group
    proportions = group / total  # Calculate the proportions
    proportions = proportions[proportions > 0]  # Filter out zero proportions
    return -np.sum(proportions * np.log(proportions))  # Calculate the Shannon Index

# Calculate the Shannon Index for each country and year (grouped by Alpha-3code and item group)
shannon_indices = grouped_data.groupby('Alpha-3code').apply(lambda x: x.apply(shannon_index))

# Calculate the average Shannon Index across years for each country (by item group)
shannon_avg = shannon_indices[year_columns].mean(axis=1).to_frame(name='shannon_avg_itemgroup')
shannon_avg = shannon_avg.reset_index()

# Merge the average Shannon Index (by item group) into the final DataFrame
final_df = final_df.merge(shannon_avg, on='Alpha-3code', how='left')

# Final DataFrame with Shannon Indices added
final_df

#################################AREA HARVESTED

yield_data = filtered_data[filtered_data['Element'] == 'Area harvested']


# Select the latest year (2021) for each crop type in each country
area_per_crop = yield_data.groupby(['Area Code (M49)', 'Item'])['Y2021'].sum().reset_index()

# Sum these values for each country
area_country = area_per_crop.groupby('Area Code (M49)')['Y2021'].sum().reset_index()

# Rename the column to 'main_Harvested_Area'
area_country.rename(columns={'Y2021': 'main_Harvested_Area'}, inplace=True)
final_df = final_df.merge(area_country[['Area Code (M49)', 'main_Harvested_Area']], on='Area Code (M49)', how='left')
#final_df=final_df.round(3)

#################### Load the AQUASTAT database
aqua = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/AQUASTAT.csv')

# List of variables of interest to include in the analysis
variables_of_interest = [
    'Population density',
    '% of the cultivated area equipped for irrigation',
    'GDP per capita',
    'Agriculture, value added (% GDP)',
    'Services, value added to GDP',
    'Industry, value added to GDP',
    'Agriculture, value added to GDP',
    'Human Development Index (HDI) [highest = 1]',
    'National Rainfall Index (NRI)',
    'Total population',
    'Rural population',
    '% of total country area cultivated',
    'Gender Inequality Index (GII) [equality = 0; inequality = 1)',

]

# Filter the rows to include only those with variables of interest
aqua_filtered = aqua[aqua['Variable'].isin(variables_of_interest)]

# Pivot the DataFrame to organize data by country ('M49') and year
aqua_pivot = aqua_filtered.pivot_table(index=['M49', 'Year'], columns='Variable', values='Value', aggfunc='first')

# Calculate '%rural' as the proportion of the rural population over the total population
aqua_pivot['%rural'] = aqua_pivot['Rural population'] / aqua_pivot['Total population']

# Filter the data for the period 1992-2020 and calculate the average for each country
aqua_period = aqua_pivot[(aqua_pivot.index.get_level_values('Year') >= 1992) & (aqua_pivot.index.get_level_values('Year') <= 2020)]
aqua_period['Year_Num'] = aqua_period.index.get_level_values('Year') - 1992 + 1  # Create a numeric year column starting at 1
aqua_period['M49B'] = aqua_period.index.get_level_values('M49')  # Extract the country code ('M49')
aqua_avg = aqua_period.groupby('M49').mean()  # Calculate the average of variables per country

############ Calculate precipitation variability
# Calculate the standard deviation of the 'National Rainfall Index (NRI)' for each country
std_nri = aqua_pivot.groupby('M49')['National Rainfall Index (NRI)'].std()

# Calculate the mean of the 'National Rainfall Index (NRI)' for each country
mean_nri = aqua_pivot.groupby('M49')['National Rainfall Index (NRI)'].mean()

# Calculate the coefficient of variation (CV) for the National Rainfall Index (NRI)
cv_nri = (std_nri / mean_nri) * 100

# Create a DataFrame to store the CV results
cv_nri_df = cv_nri.to_frame(name='CV_NRI')

###### Calculate detrended precipitation variability
# Define a function to calculate the trend slope of the 'National Rainfall Index (NRI)' for each country
def calculate_nri_slope(group):
    return stats.linregress(group['Year_Num'], group['National Rainfall Index (NRI)']).slope

# Apply the function to calculate the trend slope for each country
nri_trend_slope = aqua_period.groupby('M49B').apply(calculate_nri_slope)

# Adjust the 'National Rainfall Index (NRI)' values by removing the linear trend
aqua_period['NRI_Detrended'] = aqua_period.apply(
    lambda row: row['National Rainfall Index (NRI)'] - (nri_trend_slope[row['M49B']] * row['Year_Num']),
    axis=1
)

# Calculate the standard deviation of the detrended NRI for each country
std_nri_detrended = aqua_period.groupby('M49B')['NRI_Detrended'].std()

# Calculate the mean of the detrended NRI for each country
mean_nri_detrended = aqua_period.groupby('M49B')['NRI_Detrended'].mean()

# Calculate the coefficient of variation (CV) for the detrended NRI
cv_nri_detrended = (std_nri_detrended / mean_nri_detrended)

# Merge the calculated averages, NRI CV, and detrended NRI CV into the final DataFrame
final_df1 = final_df.merge(aqua_avg, left_on='Area Code (M49)', right_index=True, how='left')
final_df1 = final_df1.merge(cv_nri_df, left_on='Area Code (M49)', right_index=True, how='left')
final_df1 = final_df1.merge(cv_nri_detrended, left_on='Area Code (M49)', right_index=True, how='left')

# Display the first rows of the final DataFrame
final_df1.head()

################################################################ Voice and Accountability
# Load the dataset for "Voice and Accountability"
Accountability = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/VoiceandAccountability.csv')

# Identify the columns corresponding to years in the DataFrame
yeargob = [col for col in Accountability.columns if col.isdigit()]

# Filter out countries that have data in fewer than 10 years
Accountability = Accountability.dropna(thresh=10, subset=yeargob)

# Calculate the average value of "Voice and Accountability" for each country
Accountability['Accountability'] = Accountability[yeargob].mean(axis=1, skipna=True)

# Merge the results into the final DataFrame
final_df1 = final_df1.merge(Accountability[['Code', 'Accountability']], left_on='Alpha-3code', right_on='Code', how='left')

# Drop the redundant 'Code' column after merging
final_df1 = final_df1.drop(columns=['Code'])


########################################################## Rule of Law
# Load the dataset for "Rule of Law"
law = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/RuleofLaw.csv')

# Identify the columns corresponding to years in the DataFrame
yeargob = [col for col in law.columns if col.isdigit()]

# Filter out countries that have data in fewer than 10 years
law = law.dropna(thresh=10, subset=yeargob)

# Calculate the average value of "Rule of Law" for each country
law['law'] = law[yeargob].mean(axis=1, skipna=True)

# Merge the results into the final DataFrame
final_df1 = final_df1.merge(law[['Code', 'law']], left_on='Alpha-3code', right_on='Code', how='left')

# Drop the redundant 'Code' column after merging
final_df1 = final_df1.drop(columns=['Code'])


########################################################## Regulatory Quality
# Load the dataset for "Regulatory Quality"
Regulation = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/RegulatoryQuality.csv')

# Identify the columns corresponding to years in the DataFrame
yeargob = [col for col in Regulation.columns if col.isdigit()]

# Filter out countries that have data in fewer than 10 years
Regulation = Regulation.dropna(thresh=10, subset=yeargob)

# Calculate the average value of "Regulatory Quality" for each country
Regulation['Regulation'] = Regulation[yeargob].mean(axis=1, skipna=True)

# Merge the results into the final DataFrame
final_df1 = final_df1.merge(Regulation[['Code', 'Regulation']], left_on='Alpha-3code', right_on='Code', how='left')

# Drop the redundant 'Code' column after merging
final_df1 = final_df1.drop(columns=['Code'])


########################################################## Political Stability No Violence
# Load the dataset for "Political Stability No Violence"
PoliticalStability = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/ PoliticalStabilityNoViolence.csv')

# Identify the columns corresponding to years in the DataFrame
yeargob = [col for col in PoliticalStability.columns if col.isdigit()]

# Filter out countries that have data in fewer than 10 years
PoliticalStability = PoliticalStability.dropna(thresh=10, subset=yeargob)

# Calculate the average value of "Political Stability No Violence" for each country
PoliticalStability['PoliticalStability'] = PoliticalStability[yeargob].mean(axis=1, skipna=True)

# Merge the results into the final DataFrame
final_df1 = final_df1.merge(PoliticalStability[['Code', 'PoliticalStability']], left_on='Alpha-3code', right_on='Code', how='left')

# Drop the redundant 'Code' column after merging
final_df1 = final_df1.drop(columns=['Code'])


########################################################## Government Effectiveness
# Load the dataset for "Government Effectiveness"
Effectiveness = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/GovernmentEffectiveness.csv')

# Identify the columns corresponding to years in the DataFrame
yeargob = [col for col in Effectiveness.columns if col.isdigit()]

# Filter out countries that have data in fewer than 10 years
Effectiveness = Effectiveness.dropna(thresh=10, subset=yeargob)

# Calculate the average value of "Government Effectiveness" for each country
Effectiveness['Effectiveness'] = Effectiveness[yeargob].mean(axis=1, skipna=True)

# Merge the results into the final DataFrame
final_df1 = final_df1.merge(Effectiveness[['Code', 'Effectiveness']], left_on='Alpha-3code', right_on='Code', how='left')

# Drop the redundant 'Code' column after merging
final_df1 = final_df1.drop(columns=['Code'])


########################################################## Control of Corruption
# Load the dataset for "Control of Corruption"
Corruption = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/ControlofCorruption.csv')

# Identify the columns corresponding to years in the DataFrame
yeargob = [col for col in Corruption.columns if col.isdigit()]

# Filter out countries that have data in fewer than 10 years
Corruption = Corruption.dropna(thresh=10, subset=yeargob)

# Calculate the average value of "Control of Corruption" for each country
Corruption['Corruption'] = Corruption[yeargob].mean(axis=1, skipna=True)

# Merge the results into the final DataFrame
final_df1 = final_df1.merge(Corruption[['Code', 'Corruption']], left_on='Alpha-3code', right_on='Code', how='left')

# Drop the redundant 'Code' column after merging
final_df1 = final_df1.drop(columns=['Code'])

# Final DataFrame with all governance indicators
final_df1

#################### DEMOCRACY INDEX
# Load the Democracy Index dataset
democracy = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/democracy-index-eiu.csv')

# Calculate the average democracy score for each country across all available years
democ_avg = democracy.groupby('Code')['democracy_eiu'].mean().reset_index()
democ_avg = democ_avg.rename(columns={'democracy_eiu': 'Avg_democracy'})

# Merge the average democracy score into the final DataFrame
final_df1 = final_df1.merge(democ_avg, left_on='Alpha-3code', right_on='Code', how='left')


# Drop the redundant 'Code' column after merging
final_df1 = final_df1.drop(columns=['Code'])
final_df1

#################            PESTICIDES
# Load the pesticides dataset
pest = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/pesticide.csv')

# Filter the dataset to include only records from 1992 onwards
pest = pest[pest['Year'] >= 1992]


# Calculate the average pesticide value per country
pest_avg = pest.groupby('Area Code (M49)')['Value'].mean().reset_index()
pest_avg = pest_avg.rename(columns={'Value': 'Avg_pest'})

# Merge the calculated averages and trends into 'final_df1'
final_df1 = final_df1.merge(pest_avg, left_on='Area Code (M49)', right_on='Area Code (M49)', how='left')






#################            Fertilizers

# Load the fertilizers dataset
fert = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/Fertilizers.csv')

# Filter the dataset for "Nutrient nitrogen N (total)"
fert_filtered = fert[fert['Item'] == "Nutrient nitrogen N (total)"]

# Select only relevant columns: area, area code, item, and year columns
fert_filtered = fert_filtered[['Area', 'Area Code (M49)', 'Item'] + year_columns]

################ Summing fertilizer usage by country and year
# Group data by country ('Area') and area code, and sum the fertilizer values for each year
fert_sum = fert_filtered.groupby(['Area', 'Area Code (M49)'])[year_columns].sum()

# Calculate the average fertilizer usage per country
fert_avg = fert_sum.mean(axis=1)  # Mean across years
fert_avg = fert_avg.to_frame("fert_avg")  # Convert to a DataFrame with column name "fert_avg"


# Merge the average fertilizer usage into the final DataFrame
final_df1 = final_df1.merge(fert_avg, left_on='Area Code (M49)', right_on='Area Code (M49)', how='left')


# Display the first rows of the resulting DataFrame
final_df1.head()

# Load the roads dataset
roads = pd.read_csv("/content/drive/MyDrive/ColabNotebooks/input/roads_GRIP.csv")

# Select only the relevant columns: country ISO code, mean road density, and area in square kilometers
roads = roads[['isocode', 'roadsmean', 'Area(km2)']]

# Rename the column 'roadsmean' to 'roadsm_km2' for clarity
roads = roads.rename(columns={'roadsmean': 'roadsm_km2'})

# Display the keys (column names) of the dataset
roads.keys()

# Merge the roads dataset with the final DataFrame using the country ISO code ('Alpha-2code')
final_df1 = final_df1.merge(roads, left_on='Alpha-2code', right_on='isocode', how='left')

# Drop the 'isocode' column after merging as it is no longer needed
final_df1 = final_df1.drop(columns=['isocode'])

# Display the first rows of the resulting DataFrame
final_df1.head()

# Load the temperature dataset
temp = pd.read_csv("/content/drive/MyDrive/ColabNotebooks/input/Environment_Temperature_change_E_All_Data_NOFLAG.csv")

# Filter the dataset to include only rows where 'Element' is "Temperature change"
temp_filtered = temp[temp['Element'] == "Temperature change"]

# Select relevant columns: area, area code, element, and year columns
temp_filtered = temp_filtered[['Area', 'Area Code (M49)', 'Element'] + year_columns]

################ Summing temperature change data by country and year
# Group the data by country code ('Area Code (M49)') and sum temperature changes across years
temp_sum = temp_filtered.groupby(['Area Code (M49)'])[year_columns].sum()

# Calculate the average temperature change for each country
temp_avg = temp_sum.mean(axis=1)
temp_avg = temp_avg.to_frame("temp_avg")  # Convert the average to a DataFrame with column name "temp_avg"

# Calculate the coefficient of variation (CV) for temperature changes by country
cv_temp = (temp_sum.std(axis=1) / temp_sum.mean(axis=1)) * 100  # Standard deviation divided by the mean, expressed as a percentage
cv_temp = cv_temp.to_frame("cv_temp")  # Convert the CV to a DataFrame with column name "cv_temp"


# Merge the CV of temperature changes into the final DataFrame
final_df1 = final_df1.merge(cv_temp, left_on='Area Code (M49)', right_on='Area Code (M49)', how='left')

# Display the resulting DataFrame
final_df1

# Load the land cover dataset
modis = pd.read_csv("/content/drive/MyDrive/ColabNotebooks/input/Environment_LandCover_E_All_Data.csv")

# Convert the 'Area Code (M49)' column to integer after removing any quotation marks
modis['Area Code (M49)'] = modis['Area Code (M49)'].str.replace("'", '').astype(int)

# Melt the dataset to transform the year columns into rows
modis_melted = pd.melt(
    modis,
    id_vars=['Area Code', 'Area Code (M49)', 'Area', 'Item Code', 'Item', 'Element Code', 'Element', 'Unit'],
    var_name='Year',
    value_name='Value'
)

# Extract the year from the 'Year' column and convert it to an integer
modis_melted['Year'] = modis_melted['Year'].str.extract('(\d+)', expand=False).astype(int)

# Pivot the dataset to have land cover classes as columns
modis_pivoted = modis_melted.pivot_table(
    index=['Area Code', 'Area Code (M49)', 'Area', 'Year'],
    columns='Item',
    values='Value'
).reset_index()

# Calculate the total land cover for each record by summing across all land cover classes
modis_pivoted['Total_Land_Cover'] = modis_pivoted.iloc[:, 4:].sum(axis=1)

# Extract 'Area Code (M49)' and 'Area(km2)' from final_df1 for merging
keep = final_df1[['Area Code (M49)', 'Area(km2)']]
merged_df = pd.merge(keep, modis_pivoted, on='Area Code (M49)', how='inner')

# Manually set 'Area(km2)' for specific country codes if missing
area_values = {
    184: 236,
    275: 6025,
    462: 300,
    659: 260,
    670: 390,
    690: 460
}

# Update 'Area(km2)' for the specified country codes
for country_code, area in area_values.items():
    merged_df.loc[(merged_df['Area Code (M49)'] == country_code) & (merged_df['Area(km2)'].isna()), 'Area(km2)'] = area

# List of land cover columns to process
land_cover_columns = [
    'Total_Land_Cover'
]

# Convert natural areas from hectares to square kilometers (1 hectare = 0.01 km², multiply by 10)
for column in land_cover_columns:
    merged_df[column] = merged_df[column] * 10

# Normalize land cover data by dividing by the total area (km²) of the country
for column in land_cover_columns:
    merged_df[column] = merged_df[column] / merged_df['Area(km2)']

# Calculate the average land cover proportion for each country
average_land_cover = merged_df.groupby('Area Code (M49)')[land_cover_columns].mean().reset_index()

# Function to calculate the relative trend for each land cover class
def calculate_relative_trend(df):
    trends = {}
    for column in land_cover_columns:
        # Get the base value (1992) and end value (latest year) for the column
        base_value = df[df['Year'] == 1992][column].values[0]
        end_value = df[df['Year'] == df['Year'].max()][column].values[0]
        # Calculate the relative trend as the ratio of end value to base value
        trends[column + '_Trend'] = end_value / base_value
    return pd.Series(trends)

# Calculate the relative trend for each land cover class for each country
relative_trend_df = merged_df.groupby('Area Code (M49)').apply(calculate_relative_trend).reset_index()

# Fill any missing values in the trend DataFrame with zeros
relative_trend_df.fillna(0, inplace=True)

# Merge the average land cover data into the final DataFrame
final_df1 = final_df1.merge(average_land_cover, on='Area Code (M49)', how='left')

# Merge the relative trend data into the final DataFrame
final_df1 = final_df1.merge(relative_trend_df, on='Area Code (M49)', how='left')

# Display the final DataFrame
final_df1

filtered_final_df2 = final_df1[final_df1['Area(km2)']>= 20440.0]
filtered_final_df2 = filtered_final_df2 [filtered_final_df2 ['yield_flags_proportion']<= 0.8]
filtered_final_df2 =filtered_final_df2.round(3)
filtered_final_df2  = filtered_final_df2 .drop_duplicates(subset='Area', keep='first')
filtered_final_df2

from google.colab import files

filtered_final_df2 .to_csv('crops_main.csv')
files.download('crops_main.csv')
