# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.


"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import statsmodels.api as sm
# Cargar la base de datos
data_path = '/content/drive/MyDrive/ColabNotebooks/input/Production_Crops_Livestock_E_All_Data.csv'
filtered_data = pd.read_csv(data_path, encoding='latin1')


# Filtrar las columnas que contienen datos de rendimiento desde el año 2000 al 2022
year_columns = [f'Y{year}' for year in range(1992, 2022)]
flag_columns = [f'Y{year}F' for year in range(1992, 2022)]
filtered_data = filtered_data[['Area', 'Area Code (M49)', 'Item', 'Element'] + year_columns+ flag_columns]
filtered_data
selected_items= ["Barley", 	"Cassava, fresh", "Groundnuts, excluding shelled", "Maize (corn)", "Millet", 	"Oil palm fruit", "Potatoes", "Rape or colza seed", "Rice", 	"Rye", 	"Sorghum", "Soya beans", "Sugar beet", "Sugar cane", "Sunflower seed", "Wheat"]

# Cargar la tabla de grupos de ítems (para quedarme solo con los que representan cultivos)
item_groups = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/FAOSTAT_data_9-14-2023.csv')
# Lista de grupos de ítems para eliminar
groups_to_remove = ["Crops, primary", "Oilcrops, Cake Equivalent", "Oilcrops, Oil Equivalent", "Crops Processed"]
# Eliminar filas donde "Item Group" sea alguno de los valores en groups_to_remove
item_groups = item_groups[~item_groups['Item Group'].isin(groups_to_remove)]

# Mostrar las primeras filas para verificar los cambios


# Filtrar 'filtered_data' para quedarnos solo con los ítems que están en 'filtered_items'
filtered_data = filtered_data[filtered_data['Item'].isin(selected_items)]


# 1. Filtrar el conjunto de datos para incluir solo las filas con "Yield" en la columna "Element".
yield_data = filtered_data[filtered_data['Element'] == 'Area harvested']

# 2. Agrupar por país y año y verificar si hay algún dato (no NA) para ese año.
valid_countries = yield_data.groupby('Area').apply(lambda group: all(group[year_columns].notna().any())).reset_index()
valid_countries.columns = ['Area', 'Valid']

# 3. Filtrar aquellos países que tienen datos para todos los años en el rango especificado.
valid_countries_list = valid_countries[valid_countries['Valid']]['Area'].tolist()
filtered_data = filtered_data[filtered_data['Area'].isin(valid_countries_list)]



# Renombrar la columna 'Item Group' a 'item_group'
filtered_data = filtered_data.rename(columns={'Item Group': 'item_group'})

harvested_data = filtered_data[filtered_data['Element'] == 'Area harvested']

# Step 2: Calculate the average per country and item for each year
# Selecting the columns needed for the groupby and mean calculation
columns_to_keep = [ 'Area Code (M49)', 'Item'] + [f'Y{year}' for year in range(1992, 2022)]

harvested_data = harvested_data[columns_to_keep]

# Adding a new column that contains the average across all years for each row
#harvested_data['Average'] = harvested_data[year_columns].mean(axis=1)

# Now, group by 'Area' and 'Item' and take the mean of the 'Average' column
#average_data = harvested_data.groupby([ 'Area Code (M49)', 'Item'])['Average'].mean().reset_index()

harvested_data

country_codes = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/country_code.csv')
codes_to_remove = [
    "'001", "'002", "'014", "'017", "'015", "'018", "'011", "'019", "'021", "'013", "'029'", "'005",
   "'142", "'143", "'030", "'034", "'035", "'145", "'150", "'151", "'154", "'039", "'155", "'009",
    "'053", "'054", "'057", "'061", "'097","'199", "'432", "'722", "'901", "'902"
]
filtered_data =harvested_data
filtered_data['Area Code (M49)'] = filtered_data ['Area Code (M49)'].str.replace("'", '').astype(int)
# Filtrar el dataframe para eliminar las entradas con los códigos especificados
filtered_data1 = filtered_data[~filtered_data['Area Code (M49)'].isin(codes_to_remove)]
# Cargar la tabla de códigos de países
country_codes = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/country_code.csv')


# Assuming country_codes and filtered_data1 are your DataFrames
# Merge the two DataFrames on the country code
merged_data = pd.merge(filtered_data1, country_codes, left_on='Area Code (M49)', right_on='Numericcode', how='left')
merged_data = merged_data.dropna(subset=['Country'])

# Now merged_data contains information from both DataFrames
# Display the first few rows to verify the result
merged_data

import pandas as pd
from scipy import stats
yield_gap=pd.read_csv('/content/drive/MyDrive/ColabNotebooks/input/YIELD_GAP_code.csv')
# Define the base columns to keep
columns_to_keep = ['Country.Code', 'year']

# List of crops you want to keep
crops_to_keep = [
    'barley', 'cassava', 'groundnut', 'maize', 'millet', 'oilpalm',
    'potato', 'rapeseed', 'rice', 'rye', 'sorghum', 'soybean',
    'sugarbeet', 'sugarcane', 'sunflower', 'wheat'
]

# Loop through the DataFrame columns and add the ones that contain the crop names
for col in yield_gap.columns:
    for crop in crops_to_keep:
        if crop in col:
            columns_to_keep.append(col)

# Filter the DataFrame to keep only the specified columns
filtered_yield_gap = yield_gap[columns_to_keep]

# List of columns to be removed
columns_to_remove = ['buckwheat_yield', 'cassava_leaves_yield', 'green_maize_yield',
                     'other_nuts__excluding_wild_edible_nuts_and_groundnuts__in_shell__n_e_c_yield']

# Drop the specified columns
filtered_yield_gap = filtered_yield_gap.drop(columns=columns_to_remove, errors='ignore')
filtered_yield_gap.keys()

crops = [
    'barley', 'cassava', 'groundnut', 'maize', 'millet', 'oilpalm',
    'potato', 'rapeseed', 'rice', 'rye', 'sorghum', 'soybean',
    'sugarbeet', 'sugarcane', 'sunflower', 'wheat'
]

for crop in crops:
    actual_yield_col = f"{crop}_yield"
    yield_gap_col = f"{crop}_yield_gap"
    percentage_gap_col = f"{crop}_yield_gap_percentage"

    # Calculate the yield gap percentage
    # The formula is adjusted to handle the case where the denominator is 0 to avoid division by zero error
    filtered_yield_gap[percentage_gap_col] = filtered_yield_gap.apply(
        lambda row: (row[yield_gap_col] / (row[actual_yield_col] + row[yield_gap_col]))
        if (row[actual_yield_col] + row[yield_gap_col]) != 0 else 0, axis=1
    )

filtered_yield_gap

# Filter years 1992 to 2022
yield_gap_filtered =filtered_yield_gap[(filtered_yield_gap['year'] >= 1992) & (filtered_yield_gap['year'] <= 2022)]
# Filter columns
columns_to_keep = ['Country.Code', 'year'] + [col for col in yield_gap_filtered.columns if 'percentage' in col]

# Apply the filter to the DataFrame
yield_gap_filtered_subset = yield_gap_filtered[columns_to_keep]
yield_gap_filtered_subset
#yield_gap_filtered_subset.keys()

#rename columns
crop_mapping = {
    "Barley": "barley_yield_gap",
    "Cassava, fresh": "cassava_yield_gap",
    "Groundnuts, excluding shelled": "groundnut_yield_gap",
    "Maize (corn)": "maize_yield_gap",
    "Millet": "millet_yield_gap",
    "Oil palm fruit": "oilpalm_yield_gap",
    "Potatoes": "potato_yield_gap",
    "Rape or colza seed": "rapeseed_yield_gap",
    "Rice": "rice_yield_gap",
    "Rye": "rye_yield_gap",
    "Sorghum": "sorghum_yield_gap",
    "Soya beans": "soybean_yield_gap",
    "Sugar beet": "sugarbeet_yield_gap",
    "Sugar cane": "sugarcane_yield_gap",
    "Sunflower seed": "sunflower_yield_gap",
    "Wheat": "wheat_yield_gap"
}

# Apply the mapping to the 'Item' column
merged_data['StandardizedCropName'] = merged_data['Item'].map(crop_mapping)
merged_data

# Melting yield_gap_filtered_subset
yield_gap_long = pd.melt(yield_gap_filtered_subset, id_vars=['Country.Code', 'year'], var_name='StandardizedCropName', value_name='YieldGap')

# Removing the '_yield_gap' part to match the StandardizedCropName in merged_data
yield_gap_long['StandardizedCropName'] = yield_gap_long['StandardizedCropName'].str.replace('_percentage', '', regex=False)
yield_gap_long

years = [f'Y{year}' for year in range(1992, 2022)]  # Adjust depending on your data
merged_long = pd.melt(merged_data, id_vars=['Alpha-3code', 'StandardizedCropName'],
                      value_vars=years, var_name='Year', value_name='AreaHarvested')
#merged_long['StandardizedCropName'] = merged_long['StandardizedCropName'].str.replace('_yield_gap', '', regex=False)
# Convert 'Year' column to just the year number to match 'year' in yield_gap_long
merged_long['Year'] = merged_long['Year'].str[1:].astype(int)
merged_long

final_merged_data = pd.merge(merged_long, yield_gap_long,
                             left_on=['Alpha-3code', 'StandardizedCropName', 'Year'],
                             right_on=['Country.Code', 'StandardizedCropName', 'year'],
                             how='inner')

final_merged_data

harvested_notnull_yieldgap_null = final_merged_data[
    (final_merged_data['AreaHarvested'].notnull()) &
    (final_merged_data['YieldGap'].isnull())
][['Alpha-3code', 'StandardizedCropName']]

harvested_notnull_yieldgap_null

unique_country_codes =harvested_notnull_yieldgap_null ['Alpha-3code'].unique()
print("Unique country codes:")
print(unique_country_codes)

# Filter where YieldGap is not NaN but AreaHarvested is NaN
cases_per_crop = harvested_notnull_yieldgap_null.groupby('StandardizedCropName').size()
print("Cases per crop:")
print(cases_per_crop)

cases_per_country = harvested_notnull_yieldgap_null.groupby('Alpha-3code').size()
print("Cases per country:")
print(cases_per_country)

import pandas as pd

# Calculate the weighted YieldGap
final_merged_data['WeightedYieldGap'] = final_merged_data['YieldGap'] * final_merged_data['AreaHarvested']

final_merged_data

harvested_notnull_yieldgap_null = final_merged_data[
    (final_merged_data['AreaHarvested'].notnull()) &
    (final_merged_data['YieldGap'].isnull())
][['Alpha-3code', 'StandardizedCropName']]

harvested_notnull_yieldgap_null

final_merged_data_clean = final_merged_data.dropna(subset=['WeightedYieldGap'])
# Step 1: Calculate the total harvested area per country and year
final_merged_data_clean ['TotalHarvestedArea'] =final_merged_data_clean .groupby(['Alpha-3code', 'Year'])['AreaHarvested'].transform('sum')

# Step 2: Calculate the proportion for each crop
final_merged_data_clean ['HarvestedAreaProportion'] = final_merged_data_clean ['AreaHarvested'] / final_merged_data_clean ['TotalHarvestedArea']

# Step 3: Use the proportion as the weight for the yield gap
final_merged_data_clean ['WeightedYieldGap'] = final_merged_data_clean ['HarvestedAreaProportion'] * final_merged_data_clean ['YieldGap']

# Step 4: Calculate the average weighted yield gap per country and year
average_weighted_yield_gap = final_merged_data_clean.groupby(['Alpha-3code', 'Year'])['WeightedYieldGap'].sum().reset_index()

# Renaming the column for clarity
average_weighted_yield_gap.rename(columns={'WeightedYieldGap': 'AverageWeightedYieldGap'}, inplace=True)

final_merged_data_clean
# Display the results
#average_weighted_yield_gap
from google.colab import files
average_weighted_yield_gap.to_csv('Weighted_gap.csv')
files.download('Weighted_gap.csv')
